[project]
name = "ganviz"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.11"
dependencies = [
    # build
    "setuptools",
    "ninja",

    # general
    "albucore==0.0.16",
    "click",
    "gdown",
    "tqdm",
    "pillow",
    "cairosvg",

    # 3dgs
    "imagecodecs[all]>=2025.3.30",
    "pandas>=2.3.3",

    # gui
    "imgui",
    "imgui-bundle",
    "glfw",
    "requests",
    "pyopengl",
    "gputil",
    "pynvml",

    # inversion
    "lpips",
    "insightface",
    "onnxruntime",
    "numpy",
    "scipy",
    "scikit-learn",
    "matplotlib",
    "pillow",
    "imageio",
    "imageio-ffmpeg",


    # Logging / training tools
    "wandb",
    "tensorboard",
    "psutil",

    # Vision / CV
    "opencv-python",
    "pyspng",
    "plyfile",

    # 3D Gaussian rendering
    "gsplat",
    "torch",
]


[tool.uv.sources]
torch = [
  { index = "pytorch-cu130" },
]

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true
